### ISSUE TITLE
Output of count in get_elements should use status field

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [jsquyres/froozle-mpi#2]
The current mock-up uses a configure constant as the return value for get_elements[*], as in the following:
https://github.com/jsquyres/froozle-mpi/blob/d39a6f0d8db8e19869a86c386364b622b1a1bd6f/c/get_elements_int.c#L23

In a real implementation, this value would be extracted from the status struct. That actually makes the code simpler, because there can never be truncation unless the user code is erroneous.

Here's a sketch of a real implementation:
```
struct froozle_status {
    MPI_Count count;
    MPI_Datatype dt;
    MPI_Count dt_extent;
}
typedef struct froozle_status MPI_Status;

int get_elements_int(MPI_Status status, MPI_Datatype dt, int *count) {
    if (dt == status->dt)
        *count = (int)status->count;
    else
        // compute count using 128bit arithmetic from ratio of extents of dt and status->dt
        MPI_Count dt_extent;
        MPI_Type_get_extent_x(dt, &dt_extent);
        *count = (long long)status->count * (long long)status.dt_extent / dt_extent;
}
int get_elements_count(MPI_Status status, MPI_Datatype dt, MPI_Count *count) {
    if (dt == status->dt)
        *count = status->count;
    else
        // compute count using 128bit arithmetic from ratio of extents of dt and status->dt
        MPI_Count dt_extent;
        MPI_Type_get_extent_x(dt, &dt_extent);
        *count = (long long)status->count * (long long)status.dt_extent / dt_extent;
}
```

**Comment by jsquyres** [comment]
Note that MPI-3.1 p114 says that if the size of the count is too small to hold the actual value, we're supposed to just assign `MPI_UNDEFINED`, which makes the implementation fairly trivial.

Regardless, #6 is inbound to actually read from the status.
